[package]
name = "calculator"
version = "0.2.0"
authors = ["Flow Team <team@flow-lang.org>"]
description = "Calculator using mathlib with proper imports"
license = "MIT"
type = "bin"
entry = "src/main.flow"

[dependencies]
mathlib = { path = "../mathlib-improved" }

