/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flowlang_bindings_FlowModule */

#ifndef _Included_com_flowlang_bindings_FlowModule
#define _Included_com_flowlang_bindings_FlowModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    getFunction
 * Signature: (Ljava/lang/String;)Lcom/flowlang/bindings/FlowFunction;
 */
JNIEXPORT jobject JNICALL Java_com_flowlang_bindings_FlowModule_getFunction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    call
 * Signature: (Lcom/flowlang/bindings/FlowRuntime;Ljava/lang/String;[Lcom/flowlang/bindings/FlowValue;)Lcom/flowlang/bindings/FlowValue;
 */
JNIEXPORT jobject JNICALL Java_com_flowlang_bindings_FlowModule_call
  (JNIEnv *, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    freeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_flowlang_bindings_FlowModule_freeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    getFunctionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_flowlang_bindings_FlowModule_getFunctionCount
  (JNIEnv *, jobject);

/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    listFunctions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_flowlang_bindings_FlowModule_listFunctions
  (JNIEnv *, jobject);

/*
 * Class:     com_flowlang_bindings_FlowModule
 * Method:    getFunctionInfo
 * Signature: (Ljava/lang/String;)Lcom/flowlang/bindings/FlowModule/FunctionInfo;
 */
JNIEXPORT jobject JNICALL Java_com_flowlang_bindings_FlowModule_getFunctionInfo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
