version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flow_registry_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flow_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  registry:
    build: .
    container_name: flow_registry_server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      ENVIRONMENT: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: flow_registry
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      STORAGE_PATH: /app/storage/packages
    ports:
      - "8080:8080"
    volumes:
      - package_storage:/app/storage/packages
    restart: unless-stopped

volumes:
  postgres_data:
  package_storage:

