// native-math - Native C library header
// Generated by River package manager

#ifndef NATIVE_MATH_H
#define NATIVE_MATH_H

#ifdef __cplusplus
extern "C" {
#endif

// Example function: add two integers
int add(int a, int b);

// Example function: multiply two integers
int multiply(int a, int b);

// Example function: get library version
const char* get_version();

#ifdef __cplusplus
}
#endif

#endif // NATIVE_MATH_H
