// native-math - Native C library
// Generated by River package manager

#include "lib.h"

// Example function: add two integers
int add(int a, int b) {
    return a + b;
}

// Example function: multiply two integers
int multiply(int a, int b) {
    return a * b;
}

// Example function: get library version
const char* get_version() {
    return "0.1.0";
}
