name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Issue settings
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had 
            recent activity. It will be closed in 7 days if no further activity occurs.
            
            If this issue is still relevant, please add a comment to keep it open.
            Thank you for your contributions! 🙏
          close-issue-message: |
            This issue has been automatically closed due to inactivity.
            
            If you believe this issue is still relevant, please reopen it or create a new issue
            with updated information. Thank you! 🙏
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement'

          # PR settings
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            
            Please update this PR if you're still working on it, or close it if it's no longer needed.
            Thank you for your contributions! 🙏
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.
            
            If you'd like to continue working on this, please reopen it or create a new PR.
            Thank you for your contributions! 🙏
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,work-in-progress'

          # General settings
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true

